"""Meal plan endpoints."""

from fastapi import APIRouter, Depends, Query
from fastapi.responses import StreamingResponse

from app.core.exceptions import NotFoundException
from app.core.security import AuthContext, get_auth_context
from app.dependencies import ai_rate_limit, default_rate_limit, get_meal_plan_service
from app.schemas.meal_plans import (
    MealPlanGenerateRequest,
    MealPlanHistoryResponse,
    MealPlanPdfRequest,
    MealPlanResponse,
)
from app.services.meal_plan_service import MealPlanService

router = APIRouter(prefix="/meal-plans", tags=["Meal Plans"])


@router.post(
    "/generate",
    response_model=MealPlanResponse,
    summary="Generate personalized meal plan",
    description="Creates a structured meal plan based on goal, diet preferences, and constraints.",
    dependencies=[Depends(ai_rate_limit)],
)
async def generate_meal_plan(
    payload: MealPlanGenerateRequest,
    auth: AuthContext = Depends(get_auth_context),
    service: MealPlanService = Depends(get_meal_plan_service),
) -> MealPlanResponse:
    return await service.generate(auth.clerk_user_id, payload)


@router.get(
    "/history",
    response_model=MealPlanHistoryResponse,
    summary="List meal plan history",
    description="Returns recent meal plans generated by the current user.",
    dependencies=[Depends(default_rate_limit)],
)
async def list_meal_plan_history(
    limit: int = Query(default=20, ge=1, le=100),
    auth: AuthContext = Depends(get_auth_context),
    service: MealPlanService = Depends(get_meal_plan_service),
) -> MealPlanHistoryResponse:
    items = await service.get_history(auth.clerk_user_id, limit)
    return MealPlanHistoryResponse(items=items)


@router.get(
    "/history/{record_id}",
    response_model=MealPlanResponse,
    summary="Get meal plan by id",
    description="Returns one meal plan record by id for the current user.",
    dependencies=[Depends(default_rate_limit)],
)
async def get_meal_plan_by_id(
    record_id: str,
    auth: AuthContext = Depends(get_auth_context),
    service: MealPlanService = Depends(get_meal_plan_service),
) -> MealPlanResponse:
    record = await service.get_by_id(auth.clerk_user_id, record_id)
    if record is None:
        raise NotFoundException("Meal plan not found")
    return record


@router.post(
    "/{record_id}/export/pdf",
    summary="Export meal plan as PDF",
    description="Generates a PDF download from an existing meal plan record.",
    dependencies=[Depends(default_rate_limit)],
)
async def export_meal_plan_pdf(
    record_id: str,
    payload: MealPlanPdfRequest,
    auth: AuthContext = Depends(get_auth_context),
    service: MealPlanService = Depends(get_meal_plan_service),
) -> StreamingResponse:
    try:
        pdf_bytes = await service.export_pdf(auth.clerk_user_id, record_id, payload.full_name, payload.age)
    except ValueError as exc:
        raise NotFoundException(str(exc)) from exc

    filename = f"nutriai_meal_plan_{payload.full_name.replace(' ', '_').lower()}.pdf"

    return StreamingResponse(
        content=iter([pdf_bytes]),
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )
