"""Recommendation endpoints."""

from fastapi import APIRouter, Depends, Query

from app.core.security import AuthContext, get_auth_context
from app.dependencies import ai_rate_limit, default_rate_limit, get_operations_service, get_recommendation_service
from app.schemas.operations import OperationSubmitRequest
from app.schemas.recommendations import (
    RecommendationGenerateRequest,
    RecommendationHistoryResponse,
    RecommendationResponse,
)
from app.services.recommendation_service import RecommendationService

router = APIRouter(prefix="/recommendations", tags=["Recommendations"])


@router.post(
    "/generate",
    response_model=RecommendationResponse,
    summary="Generate recommendations",
    description="Generates healthier alternatives and/or healthy recipe suggestions.",
    dependencies=[Depends(ai_rate_limit)],
)
async def generate_recommendations(
    payload: RecommendationGenerateRequest,
    auth: AuthContext = Depends(get_auth_context),
    service: RecommendationService = Depends(get_recommendation_service),
    operations_service=Depends(get_operations_service),
) -> RecommendationResponse:
    operation = await operations_service.submit_and_wait(
        auth.clerk_user_id,
        OperationSubmitRequest(
            feature="recommendation_generate",
            payload=payload.model_dump(mode="json"),
        ),
    )
    return RecommendationResponse.model_validate(operation.response_payload)


@router.get(
    "/history",
    response_model=RecommendationHistoryResponse,
    summary="List recommendation history",
    description="Returns recommendation records generated by the current user.",
    dependencies=[Depends(default_rate_limit)],
)
async def get_recommendation_history(
    limit: int = Query(default=20, ge=1, le=100),
    auth: AuthContext = Depends(get_auth_context),
    service: RecommendationService = Depends(get_recommendation_service),
) -> RecommendationHistoryResponse:
    items = await service.get_history(auth.clerk_user_id, limit)
    return RecommendationHistoryResponse(items=items)
