"""Nutri Smart Picks endpoints."""

from fastapi import APIRouter, Depends, Query
from pydantic import BaseModel, Field

from app.core.security import AuthContext, get_auth_context
from app.dependencies import ai_rate_limit, default_rate_limit, get_operations_service, get_smart_picks_service
from app.schemas.operations import OperationSubmitRequest
from app.schemas.smart_picks import (
    SmartPickGenerateRequest,
    SmartPickHistoryResponse,
    SmartPickResponse,
)
from app.services.smart_picks_service import SmartPicksService

router = APIRouter(tags=["Nutri Smart Picks"])


class LegacyRecommendationGenerateRequest(BaseModel):
    query: str = Field(..., min_length=2)
    recommendation_type: str = "both"


@router.post(
    "/recommendations/generate",
    response_model=SmartPickResponse,
    summary="Generate Nutri Smart Picks",
    description="Backward-compatible endpoint for the former recommendations feature.",
    dependencies=[Depends(ai_rate_limit)],
    include_in_schema=False,
)
async def generate_smart_picks_legacy(
    payload: LegacyRecommendationGenerateRequest,
    auth: AuthContext = Depends(get_auth_context),
    operations_service=Depends(get_operations_service),
) -> SmartPickResponse:
    normalized = SmartPickGenerateRequest(
        goal="healthy_lifestyle",
        mode="situation_pick",
        situation=payload.query,
        context=payload.query,
    )
    operation = await operations_service.submit_and_wait(
        auth.clerk_user_id,
        OperationSubmitRequest(
            feature="recommendation_generate",
            payload=normalized.model_dump(mode="json"),
        ),
    )
    return SmartPickResponse.model_validate(operation.response_payload)


@router.post(
    "/nutri-smart-picks/generate",
    response_model=SmartPickResponse,
    summary="Generate Nutri Smart Picks",
    description="Ranks the best real-world food choices for a user's goal and situation.",
    dependencies=[Depends(ai_rate_limit)],
)
async def generate_smart_picks(
    payload: SmartPickGenerateRequest,
    auth: AuthContext = Depends(get_auth_context),
    operations_service=Depends(get_operations_service),
) -> SmartPickResponse:
    operation = await operations_service.submit_and_wait(
        auth.clerk_user_id,
        OperationSubmitRequest(
            feature="recommendation_generate",
            payload=payload.model_dump(mode="json"),
        ),
    )
    return SmartPickResponse.model_validate(operation.response_payload)


@router.get(
    "/nutri-smart-picks/history",
    response_model=SmartPickHistoryResponse,
    summary="List Nutri Smart Picks history",
    description="Returns Nutri Smart Picks records generated by the current user.",
    dependencies=[Depends(default_rate_limit)],
)
@router.get(
    "/recommendations/history",
    response_model=SmartPickHistoryResponse,
    summary="List Nutri Smart Picks history",
    description="Backward-compatible history endpoint for the former recommendations feature.",
    dependencies=[Depends(default_rate_limit)],
    include_in_schema=False,
)
async def get_smart_pick_history(
    limit: int = Query(default=20, ge=1, le=100),
    auth: AuthContext = Depends(get_auth_context),
    service: SmartPicksService = Depends(get_smart_picks_service),
) -> SmartPickHistoryResponse:
    items = await service.get_history(auth.clerk_user_id, limit)
    return SmartPickHistoryResponse(items=items)
